services:
  rdf4j:
    image: eclipse/rdf4j-workbench
    restart: always
    environment:
      - JAVA_OPTS=-Xms1g -Xmx4g -Dhttp.nonProxyHosts="" -Dhttp.proxyHost=outproxy -Dhttp.proxyPort=8080 -Dhttps.proxyHost=outproxy -Dhttps.proxyPort=8080
    volumes:
      - rdf4j-data:/var/rdf4j
      - rdf4j-logs:/usr/local/tomcat/logs

  nginx:
    image: nginxinc/nginx-unprivileged:latest
    restart: always
    depends_on:
      - rdf4j
      - authproxy
      - outproxy
    ports:
      - ${PUBLIC_PORT}:80
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  outproxy:
    image: ghcr.io/fau-cdi/open_gdb_outproxy:latest
    build:
      context: outproxy
    restart: always
    depends_on:
      - rdf4j

  authproxy:
    image: ghcr.io/fau-cdi/open_gdb_authproxy:latest
    build:
      context: authproxy
    restart: always
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_SUPERUSER_NAME=${DJANGO_SUPERUSER_NAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
    depends_on:
      - rdf4j
    volumes:
      - authproxy-data:/data/

volumes:
  rdf4j-data:
  rdf4j-logs:
  authproxy-data:
