# Generated by Django 5.0.4 on 2025-11-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rdf4j", "0002_alter_repository_turtle_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="turtle_template",
            field=models.TextField(
                default='@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.\n@prefix config: <tag:rdf4j.org,2023:config/>.\n[] a config:Repository ;\nconfig:rep.id "${slug}" ;\nrdfs:label "${description}" ;\nconfig:rep.impl [\n    config:rep.type "openrdf:SailRepository" ;\n    config:sail.impl [\n        config:sail.type "openrdf:NativeStore" ;\n        config:native.tripleIndexes "spoc,posc"\n    ]\n].',
                help_text="Template for the repo creation, passed though to RDF4J.\nAvailable variables:\n- ${slug}: The slug of the repo\n- ${description}: The description of the repo\n",
                null=True,
            ),
        ),
    ]
